<?php

class Tax_Map {
    public $wrongcats = [
        "Trailer Pumps Concrete Pumps" => "Trailer Pumps",
        "Boom Pump" => "Boom Pumps",
        "Other Cranes" => "Cranes",
        "Tower Cranes" => "Cranes",
        "Truck Mounted Cranes" => "Cranes",
        "Knuckle Boom Cranes" => "Cranes",
        "hydro demolition" => "Hydro Demolition",
        "Pressure Washers" => "Pressure Washing",
    ];


    public $subcats = [
        'Laser Screeds' => 'laser-screeds',
        'Truss Screeds' => 'truss-screeds',
        '3D Profiling Systems' => '3d-profiling-systems',
        'Belt Trucks or Telebelts' => 'belt-trucks',
        'Concrete Buckets' => 'concrete-buckets',
        'Concrete Buggies' => 'concrete-buggies',
        'Concrete Finishing Tools' => 'concrete-finishing-tools',
        'Concrete Vibrators' => 'concrete-vibrators',
        'Line Handling Equipment' => 'line-handling-equipment',
        'Portable Conveyers' => 'portable-conveyers',
        'Ride on Power Trowels' => 'ride-on-power-trowels',
        'Roller Screeds' => 'roller-screeds',
        'Slipform Pavers and Curbers' => 'slip-form-pavers',
        'Walk Behind Power Tools' => 'concrete-placing-equipment',
        'Belt Trucks' => 'concrete-placing-equipment',

        'Trailer Pumps' => 'concrete-pumping-equipment',
        'Trailer Pumps Concrete Pumps' => 'concrete-pumping-equipment', // fix

        'Forklifts and Telehandlers' => 'general-equipment',
        'Air Compressors' => 'general-equipment',
        'Concrete Heaters' => 'general-equipment',
        'Concrete Reclaimers' => 'general-equipment',
        'Concrete Washout' => 'general-equipment',
        'Dust Control' => 'general-equipment',
        'Fuel Storage' => 'general-equipment',
        'Generators' => 'general-equipment',
        'Ground Heaters' => 'general-equipment',
        'Light Towers' => 'general-equipment',
        'Man Lifts or Work Platforms' => 'general-equipment',
        'Pressure Washing' => 'general-equipment',
        'Rebar Machines' => 'general-equipment',
        'Scaffolding' => 'general-equipment',
        'Stone Slingers' => 'general-equipment',
        'Sweepers and Brooms' => 'general-equipment',
        'Trailers' => 'general-equipment',
        'Trucks' => 'general-equipment',
        'Vacuums or Dust Extractors' => 'general-equipment',
        'Welding Equipment' => 'general-equipment',
        'Backhoes' => 'general-equipment',
        'Compact Track Loaders' => 'general-equipment',
        'Dozers' => 'general-equipment',
        'Excavators' => 'general-equipment',
        'Skid Steer Attachments' => 'general-equipment',
        'Pier Drilling or Foundation Drilling' => 'general-equipment',
        'Trenchers' => 'general-equipment',
        'Dust Control Equipment' => 'general-equipment',
        'Cranes' => 'general-equipment',
        'Tower Cranes' => 'general-equipment',

        'Concrete Breakers' => 'concrete-demolition-equipment',
        'Concrete Drills Core Drills' => 'concrete-demolition-equipment',
        'Concrete Saws' => 'concrete-demolition-equipment',
        'Hydro Demolition' => 'concrete-demolition-equipment',
        'Jack Hammers' => 'concrete-demolition-equipment',

        'Stationary Cement Silos' => 'concrete-batching-equipment',
        'Portable Cement Silos' => 'concrete-batching-equipment',
        'Cellular Foam Plants' => 'concrete-batching-equipment',
        'Cemement Blending Equipment' => 'concrete-batching-equipment',
        'Cemement Transport Storage' => 'concrete-batching-equipment',
        'Concrete Batch Plants' => 'concrete-batching-equipment',
        'Batch Plants' => 'concrete-batching-equipment',
        'Concrete Volumetric Mixers' => 'concrete-batching-equipment',
        'Concrete Mixers' => 'concrete-batching-equipment',
        'Concrete Mobile Mixers' => 'concrete-batching-equipment',

        'Concrete Wall Forms' => 'other-concrete-equipment',
        'Other Gunite Equipment' => 'other-concrete-equipment',
        'Other Precast Equipment' => 'other-concrete-equipment',
        'Precast Molds' => 'other-concrete-equipment',
        'Precast Batching' => 'other-concrete-equipment',
        'Precast Plants' => 'other-concrete-equipment',
        'Concrete Engraving' => 'other-concrete-equipment',
        'Volumetric Gunite Mixer' => 'other-concrete-equipment',
        'Concrete Paving Forms' => 'other-concrete-equipment',
        'Other Concrete Forms' => 'other-concrete-equipment',
        'Concrete Stamp Tools' => 'other-concrete-equipment',
        'Other Concrete Related Equipment' => 'other-concrete-equipment',
        'Concrete Polishing and Grinding' => 'other-concrete-equipment',
    ];

    public $mysecondcategory = [
        'Concrete Batching and Production Equipment' => 'concrete-equipment-type'
    ];

    public $tax_slugs = [
        'Laser Screeds' => 'placing-equipment-type',
        'Truss Screeds' => 'placing-equipment-type',
        '3D Profiling Systems' => 'placing-equipment-type',
        'Belt Trucks or Telebelts' => 'placing-equipment-type',
        'Concrete Buckets' => 'placing-equipment-type',
        'Concrete Buggies' => 'placing-equipment-type',
        'Concrete Finishing Tools' => 'placing-equipment-type',
        'Concrete Vibrators' => 'placing-equipment-type',
        'Line Handling Equipment' => 'placing-equipment-type',
        'Portable Conveyers' => 'placing-equipment-type',
        'Ride on Power Trowels' => 'placing-equipment-type',
        'Roller Screeds' => 'placing-equipment-type',
        'Slipform Pavers and Curbers' => 'placing-equipment-type',
        'Walk Behind Power Tools' => 'placing-equipment-type',
        'Belt Trucks' => 'placing-equipment-type',

        'Trailer Pumps' => 'concrete-pumping-equipment',
        'Trailer Pumps Concrete Pumps' => 'concrete-pumping-equipment', // fix

        'Forklifts and Telehandlers' => 'general-equipment',
        'Air Compressors' => 'general-equipment',
        'Concrete Heaters' => 'general-equipment',
        'Concrete Reclaimers' => 'general-equipment',
        'Concrete Washout' => 'general-equipment',
        'Dust Control' => 'general-equipment',
        'Fuel Storage' => 'general-equipment',
        'Generators' => 'general-equipment',
        'Ground Heaters' => 'general-equipment',
        'Light Towers' => 'general-equipment',
        'Man Lifts or Work Platforms' => 'general-equipment',
        'Pressure Washing' => 'general-equipment',
        'Rebar Machines' => 'general-equipment',
        'Scaffolding' => 'general-equipment',
        'Stone Slingers' => 'general-equipment',
        'Sweepers and Brooms' => 'general-equipment',
        'Trailers' => 'general-equipment',
        'Trucks' => 'general-equipment',
        'Vacuums or Dust Extractors' => 'general-equipment',
        'Welding Equipment' => 'general-equipment',
        'Backhoes' => 'general-equipment',
        'Compact Track Loaders' => 'general-equipment',
        'Dozers' => 'general-equipment',
        'Excavators' => 'general-equipment',
        'Skid Steer Attachments' => 'general-equipment',
        'Pier Drilling or Foundation Drilling' => 'general-equipment',
        'Trenchers' => 'general-equipment',
        'Dust Control Equipment' => 'general-equipment',
        'Cranes' => 'general-equipment',
        'Tower Cranes' => 'general-equipment',

        'Concrete Breakers' => 'concrete-demolition-equipment',
        'Concrete Drills Core Drills' => 'concrete-demolition-equipment',
        'Concrete Saws' => 'concrete-demolition-equipment',
        'Hydro Demolition' => 'concrete-demolition-equipment',
        'Jack Hammers' => 'concrete-demolition-equipment',

        'Stationary Cement Silos' => 'concrete-batching-equipment',
        'Portable Cement Silos' => 'concrete-batching-equipment',
        'Cellular Foam Plants' => 'concrete-batching-equipment',
        'Cemement Blending Equipment' => 'concrete-batching-equipment',
        'Cemement Transport Storage' => 'concrete-batching-equipment',
        'Concrete Batch Plants' => 'concrete-batching-equipment',
        'Batch Plants' => 'concrete-batching-equipment',
        'Concrete Volumetric Mixers' => 'concrete-batching-equipment',
        'Concrete Mixers' => 'concrete-batching-equipment',
        'Concrete Mobile Mixers' => 'concrete-batching-equipment',

        'Concrete Wall Forms' => 'other-concrete-equipment',
        'Other Gunite Equipment' => 'other-concrete-equipment',
        'Other Precast Equipment' => 'other-concrete-equipment',
        'Precast Molds' => 'other-concrete-equipment',
        'Precast Batching' => 'other-concrete-equipment',
        'Precast Plants' => 'other-concrete-equipment',
        'Concrete Engraving' => 'other-concrete-equipment',
        'Volumetric Gunite Mixer' => 'other-concrete-equipment',
        'Concrete Paving Forms' => 'other-concrete-equipment',
        'Other Concrete Forms' => 'other-concrete-equipment',
        'Concrete Stamp Tools' => 'other-concrete-equipment',
        'Other Concrete Related Equipment' => 'other-concrete-equipment',
        'Concrete Polishing and Grinding' => 'other-concrete-equipment',
    ];

    public $cat_map = [
        'Laser Screeds' => 'concrete-equipment',
        'Truss Screeds' => 'concrete-equipment',
        '3D Profiling Systems' => 'concrete-equipment',
        'Belt Trucks or Telebelts' => 'concrete-equipment',
        'Concrete Buckets' => 'concrete-equipment',
        'Concrete Buggies' => 'concrete-equipment',
        'Concrete Finishing Tools' => 'concrete-equipment',
        'Concrete Vibrators' => 'concrete-equipment',
        'Line Handling Equipment' => 'concrete-equipment',
        'Portable Conveyers' => 'concrete-equipment',
        'Ride on Power Trowels' => 'concrete-equipment',
        'Roller Screeds' => 'concrete-equipment',
        'Slipform Pavers and Curbers' => 'concrete-equipment',
        'Walk Behind Power Tools' => 'concrete-equipment',
        'Belt Trucks' => 'concrete-equipment',

        'Trailer Pumps' => 'concrete-equipment',
        'Trailer Pumps Concrete Pumps' => 'concrete-equipment', // fix

        'Forklifts and Telehandlers' => 'concrete-equipment',
        'Air Compressors' => 'concrete-equipment',
        'Concrete Heaters' => 'concrete-equipment',
        'Concrete Reclaimers' => 'concrete-equipment',
        'Concrete Washout' => 'concrete-equipment',
        'Dust Control' => 'concrete-equipment',
        'Fuel Storage' => 'concrete-equipment',
        'Generators' => 'concrete-equipment',
        'Ground Heaters' => 'concrete-equipment',
        'Light Towers' => 'concrete-equipment',
        'Man Lifts or Work Platforms' => 'concrete-equipment',
        'Pressure Washing' => 'concrete-equipment',
        'Rebar Machines' => 'concrete-equipment',
        'Scaffolding' => 'concrete-equipment',
        'Stone Slingers' => 'concrete-equipment',
        'Sweepers and Brooms' => 'concrete-equipment',
        'Trailers' => 'concrete-equipment',
        'Trucks' => 'concrete-equipment',
        'Vacuums or Dust Extractors' => 'concrete-equipment',
        'Welding Equipment' => 'concrete-equipment',
        'Backhoes' => 'concrete-equipment',
        'Compact Track Loaders' => 'concrete-equipment',
        'Dozers' => 'concrete-equipment',
        'Excavators' => 'concrete-equipment',
        'Skid Steer Attachments' => 'concrete-equipment',
        'Pier Drilling or Foundation Drilling' => 'concrete-equipment',
        'Trenchers' => 'concrete-equipment',
        'Dust Control Equipment' => 'concrete-equipment',
        'Cranes' => 'concrete-equipment',
        'Tower Cranes' => 'concrete-equipment',

        'Concrete Breakers' => 'concrete-equipment',
        'Concrete Drills Core Drills' => 'concrete-equipment',
        'Concrete Saws' => 'concrete-equipment',
        'Hydro Demolition' => 'concrete-equipment',
        'Jack Hammers' => 'concrete-equipment',

        'Stationary Cement Silos' => 'concrete-equipment',
        'Portable Cement Silos' => 'concrete-equipment',
        'Cellular Foam Plants' => 'concrete-equipment',
        'Cemement Blending Equipment' => 'concrete-equipment',
        'Cemement Transport Storage' => 'concrete-equipment',
        'Concrete Batch Plants' => 'concrete-equipment',
        'Batch Plants' => 'concrete-equipment',
        'Concrete Volumetric Mixers' => 'concrete-equipment',
        'Concrete Mixers' => 'concrete-equipment',
        'Concrete Mobile Mixers' => 'concrete-equipment',

        'Concrete Wall Forms' => 'concrete-equipment',
        'Other Gunite Equipment' => 'concrete-equipment',
        'Other Precast Equipment' => 'concrete-equipment',
        'Precast Molds' => 'concrete-equipment',
        'Precast Batching' => 'concrete-equipment',
        'Precast Plants' => 'concrete-equipment',
        'Concrete Engraving' => 'concrete-equipment',
        'Volumetric Gunite Mixer' => 'concrete-equipment',
        'Concrete Paving Forms' => 'concrete-equipment',
        'Other Concrete Forms' => 'concrete-equipment',
        'Concrete Stamp Tools' => 'concrete-equipment',
        'Other Concrete Related Equipment' => 'concrete-equipment',
        'Concrete Polishing and Grinding' => 'concrete-equipment',
    ];
}
